// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package response

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson99896f1DecodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(in *jlexer.Lexer, out *EventTrackers) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "event":
			out.Event = EventType(in.Int())
		case "method":
			out.Method = EventTrackingMethod(in.Int())
		case "url":
			out.Url = string(in.String())
		case "customdata":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.CustomData = make(map[string]interface{})
				} else {
					out.CustomData = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 interface{}
					if m, ok := v1.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v1.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v1 = in.Interface()
					}
					(out.CustomData)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "ext":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Ext).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson99896f1EncodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(out *jwriter.Writer, in EventTrackers) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Event))
	}
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix)
		out.Int(int(in.Method))
	}
	if in.Url != "" {
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.Url))
	}
	if len(in.CustomData) != 0 {
		const prefix string = ",\"customdata\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v2First := true
			for v2Name, v2Value := range in.CustomData {
				if v2First {
					v2First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v2Name))
				out.RawByte(':')
				if m, ok := v2Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v2Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v2Value))
				}
			}
			out.RawByte('}')
		}
	}
	if len(in.Ext) != 0 {
		const prefix string = ",\"ext\":"
		out.RawString(prefix)
		out.Raw((in.Ext).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EventTrackers) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson99896f1EncodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventTrackers) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson99896f1EncodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventTrackers) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson99896f1DecodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventTrackers) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson99896f1DecodeGithubComOctoclickOpenrtbEasyjsonNativeResponse(l, v)
}
